spring:
  application:
    name: api-gateway
  profiles:
    include:
      - redis
      - datasource
      - eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://132.232.36.151:8761/eureka/

server:
  port: 8089

zuul:
  routes:
    login-service:
      path: /login-service/**
      serviceId: LOGIN-SERIVCE
    card-provider:
      path: /card-service/**
      serviceId: CARD-PROVIDER
    album-provier:
      path: /album-service/**
      serviceId: ALBUM-PROVIDER
    article-provider:
      path: /article-service/**
      serviceId: ARTICLE-PROVIDER
    photo-provider:
      path: /photo-service/**
      serviceId: PHOTO-PROVIDER
    user-service:
      path: /user-service/**
      serviceId: USER-SERVICE
  prefix: /api

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000

photo-provider:
  ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 80000
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 80000