spring:
  application:
    name: api-gateway
  profiles:
    include:
      - redis
      - datasource
      - eureka

server:
  port: 8089

zuul:
  routes:
    login-service:
      path: /login-service/**
      serviceId: LOGIN-SERIVCE
    card-provider:
      path: /card-service/**
      serviceId: CARD-PROVIDER
    album-provier:
      path: /album-service/**
      serviceId: ALBUM-PROVIDER
    article-provider:
      path: /article-service/**
      serviceId: ARTICLE-PROVIDER
    photo-provider:
      path: /photo-service/**
      serviceId: PHOTO-PROVIDER
    user-service:
      path: /user-service/**
      serviceId: USER-SERVICE
  prefix: /api
  sensitive-headers: '*'
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000

hystrix:
  command:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 5000
