spring:
  application:
    name: api-gateway
  profiles:
    include:
      - redis
      - datasource
      - eureka

server:
  port: 8089

zuul:
  routes:
    login-service:
      path: /login-service/**
      serviceId: LOGIN-SERIVCE
    card-provider:
      path: /card-service/**
      serviceId: CARD-PROVIDER
    album-provier:
      path: /album-service/**
      serviceId: ALBUM-PROVIDER
    article-provider:
      path: /article-service/**
      serviceId: ARTICLE-PROVIDER
    photo-provider:
      path: /photo-service/**
      serviceId: PHOTO-PROVIDER
    user-service:
      path: /user-service/**
      serviceId: USER-SERVICE
  prefix: /api
  sensitive-headers: '*'


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
