server:
  port: 8081
spring:
  application:
    name: user-service
  profiles:
    include:
      - datasource
      - mybatis
eureka:
  client:
    serviceUrl:
      defaultZone: http://45.77.16.125:8301/eureka