server:
  port: 8081
spring:
  application:
    name: user-service
  profiles:
    include:
      - datasource
      - mybatis
      - eureka
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
        - 10.0
      ignoredInterfaces:
        - docker0
        - veth.*