server:
  port: 8086
spring:
  application:
    name: card-provider
  profiles:
    include:
      - datasource
      - mybatis

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 132.232.36.151
  client:
    serviceUrl:
      defaultZone: http://132.232.36.151:8761/eureka/