server:
  port: 8086
spring:
  application:
    name: card-provider
  profiles:
    include:
      - datasource
      - mybatis
      - eureka
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
        - 10.0
      ignoredInterfaces:
        - docker0
        - veth.*