server:
  port: 8086
spring:
  application:
    name: card-provider
  profiles:
    include:
      - datasource
      - mybatis
      - eureka
  security:
    user:
      name: admin
      password: admin
      roles: admin
