server:
  port: 8084
spring:
  application:
    name: album-provider
  profiles:
    include:
      - mybatis
      - datasource

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 132.232.36.151
  client:
    serviceUrl:
      defaultZone: http://132.232.36.151:8761/eureka/