server:
  port: 8085
spring:
  application:
    name: login-serivce
  profiles:
    include:
      - datasource
      - mybatis
      - redis
      - eureka
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
        - 10.0
      ignoredInterfaces:
        - docker0
        - veth.*