server:
  port: 8085
spring:
  application:
    name: login-serivce
  profiles:
    include:
      - datasource
      - mybatis
      - redis
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 132.232.36.151
  client:
    serviceUrl:
      defaultZone: http://132.232.36.151:8761/eureka/